# Site wide configuration

title: Site Title
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: "Chelle Gentemann"
  avatar: bio-photo.jpg
  bio: "I am a passionate advocate for open science, open source software, and inclusivity.  As a physical oceanographer focused on remote sensing, I have worked for over 25 years on retrievals of ocean temperature from space and using that data to understand how the ocean impacts our lives.  My more recent research focuses on interdisciplinary science using cloud computing, open source software algorithm development, air-sea fluxes, biophysical interactions, and upper ocean physical processes.  I have served on scientific committees, notably as co-chair of a standing committee for the National Academy of Sciences and has presented to a federal house committee on NASA's implementation of scientific community priorities.
  email: cgentemann@faralloninstitute.org
  # Do not include the @ symbol in your Twitter username
  twitter: chellegentemann
  linkedin: chelle-gentemann
  github: cgentemann
  orcid: 0000-0002-2250-3106
  researchgate: cgentemann@gmail.com
  mendeley: #username
  google:
    plus: cgentemann@gmail.com
    analytics:
    verify:
    scholar: faDmNjoAAAAJ&hl
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: #yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
